[tox]
envlist = py312

[flake8]
max-line-length = 120
exclude = .tox,.venv,.git,__pycache__,build,dist
ignore = D10, W503

[testenv]
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/requirements_test.txt
commands =
    pytest src/tests --timeout=5
    flake8 src
